//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastbootEnhance.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FastbootEnhance.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fastboot Enhance 的本地化字符串。
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author: LibXZR @ akr-developers.com 的本地化字符串。
        /// </summary>
        public static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string disabled {
            get {
                return ResourceManager.GetString("disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string enabled {
            get {
                return ResourceManager.GetString("enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        public static string fastboot_0_size {
            get {
                return ResourceManager.GetString("fastboot_0_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic Properties 的本地化字符串。
        /// </summary>
        public static string fastboot_basic_prop {
            get {
                return ResourceManager.GetString("fastboot_basic_prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double click to choose the target device: 的本地化字符串。
        /// </summary>
        public static string fastboot_choose_device {
            get {
                return ResourceManager.GetString("fastboot_choose_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Virtual A/B temporary partitions exist 的本地化字符串。
        /// </summary>
        public static string fastboot_cow_exist_str0 {
            get {
                return ResourceManager.GetString("fastboot_cow_exist_str0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The temporary partitions created during the Virtual A/B system update exist in the device, forcing it to continue may cause the flashing to fail due to insufficient space in the super partition, and thus brick the device. 的本地化字符串。
        /// </summary>
        public static string fastboot_cow_exist_str1 {
            get {
                return ResourceManager.GetString("fastboot_cow_exist_str1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ( You can manually delete the temporary partitions ending in &quot;cow&quot; to resolve this warning if the Virtual A/B update is not in progress ) 的本地化字符串。
        /// </summary>
        public static string fastboot_cow_exist_str2 {
            get {
                return ResourceManager.GetString("fastboot_cow_exist_str2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Would you like to continue? 的本地化字符串。
        /// </summary>
        public static string fastboot_cow_exist_str3 {
            get {
                return ResourceManager.GetString("fastboot_cow_exist_str3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create new logical partition 的本地化字符串。
        /// </summary>
        public static string fastboot_create_dynamic_partition {
            get {
                return ResourceManager.GetString("fastboot_create_dynamic_partition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Device:  的本地化字符串。
        /// </summary>
        public static string fastboot_current_device {
            get {
                return ResourceManager.GetString("fastboot_current_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Slot 的本地化字符串。
        /// </summary>
        public static string fastboot_current_slot {
            get {
                return ResourceManager.GetString("fastboot_current_slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device 的本地化字符串。
        /// </summary>
        public static string fastboot_device {
            get {
                return ResourceManager.GetString("fastboot_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Name 的本地化字符串。
        /// </summary>
        public static string fastboot_device_name {
            get {
                return ResourceManager.GetString("fastboot_device_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target device is not exist 的本地化字符串。
        /// </summary>
        public static string fastboot_device_not_exist {
            get {
                return ResourceManager.GetString("fastboot_device_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fastboot Visualization 的本地化字符串。
        /// </summary>
        public static string fastboot_enhance {
            get {
                return ResourceManager.GetString("fastboot_enhance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand logical partition 的本地化字符串。
        /// </summary>
        public static string fastboot_expand_dynamic_partition {
            get {
                return ResourceManager.GetString("fastboot_expand_dynamic_partition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter by name: 的本地化字符串。
        /// </summary>
        public static string fastboot_filter_by_partition_name {
            get {
                return ResourceManager.GetString("fastboot_filter_by_partition_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flash Payload.bin 的本地化字符串。
        /// </summary>
        public static string fastboot_flash_payload {
            get {
                return ResourceManager.GetString("fastboot_flash_payload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore Unknown Partitions 的本地化字符串。
        /// </summary>
        public static string fastboot_ignore_unknown {
            get {
                return ResourceManager.GetString("fastboot_ignore_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In Fastbootd 的本地化字符串。
        /// </summary>
        public static string fastboot_is_userspace {
            get {
                return ResourceManager.GetString("fastboot_is_userspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operation does not allow multiple partitions to be selected. 的本地化字符串。
        /// </summary>
        public static string fastboot_not_support_multiselect {
            get {
                return ResourceManager.GetString("fastboot_not_support_multiselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operation is only supported for logical partitions. 的本地化字符串。
        /// </summary>
        public static string fastboot_only_logical {
            get {
                return ResourceManager.GetString("fastboot_only_logical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Actions 的本地化字符串。
        /// </summary>
        public static string fastboot_partition_action {
            get {
                return ResourceManager.GetString("fastboot_partition_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        public static string fastboot_partition_action_create {
            get {
                return ResourceManager.GetString("fastboot_partition_action_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string fastboot_partition_action_delete {
            get {
                return ResourceManager.GetString("fastboot_partition_action_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Erase 的本地化字符串。
        /// </summary>
        public static string fastboot_partition_action_erase {
            get {
                return ResourceManager.GetString("fastboot_partition_action_erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flash 的本地化字符串。
        /// </summary>
        public static string fastboot_partition_action_flash {
            get {
                return ResourceManager.GetString("fastboot_partition_action_flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resize 的本地化字符串。
        /// </summary>
        public static string fastboot_partition_action_resize {
            get {
                return ResourceManager.GetString("fastboot_partition_action_resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is Logical 的本地化字符串。
        /// </summary>
        public static string fastboot_partition_is_dynamic {
            get {
                return ResourceManager.GetString("fastboot_partition_is_dynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string fastboot_partition_name {
            get {
                return ResourceManager.GetString("fastboot_partition_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partition name is empty. 的本地化字符串。
        /// </summary>
        public static string fastboot_partition_name_empty {
            get {
                return ResourceManager.GetString("fastboot_partition_name_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        public static string fastboot_partition_size {
            get {
                return ResourceManager.GetString("fastboot_partition_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size (B) 的本地化字符串。
        /// </summary>
        public static string fastboot_partition_size_b {
            get {
                return ResourceManager.GetString("fastboot_partition_size_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partition size is empty. 的本地化字符串。
        /// </summary>
        public static string fastboot_partition_size_empty {
            get {
                return ResourceManager.GetString("fastboot_partition_size_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid partition size. 的本地化字符串。
        /// </summary>
        public static string fastboot_partition_size_invalid {
            get {
                return ResourceManager.GetString("fastboot_partition_size_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to shrink a partition. You can delete and recreate it. 的本地化字符串。
        /// </summary>
        public static string fastboot_partition_size_unable_shrink {
            get {
                return ResourceManager.GetString("fastboot_partition_size_unable_shrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partitions 的本地化字符串。
        /// </summary>
        public static string fastboot_partition_table {
            get {
                return ResourceManager.GetString("fastboot_partition_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string fastboot_prop_name {
            get {
                return ResourceManager.GetString("fastboot_prop_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        public static string fastboot_prop_value {
            get {
                return ResourceManager.GetString("fastboot_prop_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reboot to BootLoader 的本地化字符串。
        /// </summary>
        public static string fastboot_reboot_bootloader {
            get {
                return ResourceManager.GetString("fastboot_reboot_bootloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reboot to Fastbootd 的本地化字符串。
        /// </summary>
        public static string fastboot_reboot_fastbootd {
            get {
                return ResourceManager.GetString("fastboot_reboot_fastbootd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reboot to Recovery 的本地化字符串。
        /// </summary>
        public static string fastboot_reboot_recovery {
            get {
                return ResourceManager.GetString("fastboot_reboot_recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reboot to System 的本地化字符串。
        /// </summary>
        public static string fastboot_reboot_system {
            get {
                return ResourceManager.GetString("fastboot_reboot_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnect 的本地化字符串。
        /// </summary>
        public static string fastboot_remove_device {
            get {
                return ResourceManager.GetString("fastboot_remove_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seamless Update 的本地化字符串。
        /// </summary>
        public static string fastboot_seamless_update {
            get {
                return ResourceManager.GetString("fastboot_seamless_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Secure Boot 的本地化字符串。
        /// </summary>
        public static string fastboot_secure_boot {
            get {
                return ResourceManager.GetString("fastboot_secure_boot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial Number 的本地化字符串。
        /// </summary>
        public static string fastboot_serial_num {
            get {
                return ResourceManager.GetString("fastboot_serial_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Activate Slot A 的本地化字符串。
        /// </summary>
        public static string fastboot_setactive_a {
            get {
                return ResourceManager.GetString("fastboot_setactive_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Activate Slot B 的本地化字符串。
        /// </summary>
        public static string fastboot_setactive_b {
            get {
                return ResourceManager.GetString("fastboot_setactive_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show logs 的本地化字符串。
        /// </summary>
        public static string fastboot_show_logs {
            get {
                return ResourceManager.GetString("fastboot_show_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target partition not yet selected. 的本地化字符串。
        /// </summary>
        public static string fastboot_target_partition_not_selected {
            get {
                return ResourceManager.GetString("fastboot_target_partition_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following partitions to flash may be unknown: 的本地化字符串。
        /// </summary>
        public static string fastboot_unknown_partition_str0 {
            get {
                return ResourceManager.GetString("fastboot_unknown_partition_str0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can check the &quot;Ignore unknown partitions&quot; checkbox to disable this warning, the presence of unknown partitions does not mean that the flashing will fail or the device will brick. 的本地化字符串。
        /// </summary>
        public static string fastboot_unknown_partition_str1 {
            get {
                return ResourceManager.GetString("fastboot_unknown_partition_str1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You may need to reboot to fastbootd mode. 的本地化字符串。
        /// </summary>
        public static string fastboot_unknown_partition_str2 {
            get {
                return ResourceManager.GetString("fastboot_unknown_partition_str2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Update Status 的本地化字符串。
        /// </summary>
        public static string fastboot_update_status {
            get {
                return ResourceManager.GetString("fastboot_update_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merging 的本地化字符串。
        /// </summary>
        public static string fastboot_update_status_merging {
            get {
                return ResourceManager.GetString("fastboot_update_status_merging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string fastboot_update_status_none {
            get {
                return ResourceManager.GetString("fastboot_update_status_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snapshotted 的本地化字符串。
        /// </summary>
        public static string fastboot_update_status_snapshotted {
            get {
                return ResourceManager.GetString("fastboot_update_status_snapshotted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System update is in progress 的本地化字符串。
        /// </summary>
        public static string fastboot_vab_staging_str0 {
            get {
                return ResourceManager.GetString("fastboot_vab_staging_str0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The device is in the process of system update, forcing the operation may brick the device. 的本地化字符串。
        /// </summary>
        public static string fastboot_vab_staging_str1 {
            get {
                return ResourceManager.GetString("fastboot_vab_staging_str1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ( You can reboot the device to the system and wait a while until the update process is complete ) 的本地化字符串。
        /// </summary>
        public static string fastboot_vab_staging_str2 {
            get {
                return ResourceManager.GetString("fastboot_vab_staging_str2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Would you like to continue? 的本地化字符串。
        /// </summary>
        public static string fastboot_vab_staging_str3 {
            get {
                return ResourceManager.GetString("fastboot_vab_staging_str3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Would you like to disable the verification in vbmeta? 的本地化字符串。
        /// </summary>
        public static string fastboot_vbmeta_disable_verify {
            get {
                return ResourceManager.GetString("fastboot_vbmeta_disable_verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable verification 的本地化字符串。
        /// </summary>
        public static string fastboot_vbmeta_disable_verify_title {
            get {
                return ResourceManager.GetString("fastboot_vbmeta_disable_verify_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logger 的本地化字符串。
        /// </summary>
        public static string logger {
            get {
                return ResourceManager.GetString("logger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opensource 的本地化字符串。
        /// </summary>
        public static string open_source {
            get {
                return ResourceManager.GetString("open_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation completed 的本地化字符串。
        /// </summary>
        public static string operation_completed {
            get {
                return ResourceManager.GetString("operation_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation is not supported. 的本地化字符串。
        /// </summary>
        public static string operation_not_supported {
            get {
                return ResourceManager.GetString("operation_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic Properties 的本地化字符串。
        /// </summary>
        public static string payload_basic_properties {
            get {
                return ResourceManager.GetString("payload_basic_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blocksize 的本地化字符串。
        /// </summary>
        public static string payload_blocksize {
            get {
                return ResourceManager.GetString("payload_blocksize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string payload_browse {
            get {
                return ResourceManager.GetString("payload_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current file:  的本地化字符串。
        /// </summary>
        public static string payload_current_file {
            get {
                return ResourceManager.GetString("payload_current_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Blobs Size 的本地化字符串。
        /// </summary>
        public static string payload_data_size {
            get {
                return ResourceManager.GetString("payload_data_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payload Dumper 的本地化字符串。
        /// </summary>
        public static string payload_dumper {
            get {
                return ResourceManager.GetString("payload_dumper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dynamic Partition Metadata 的本地化字符串。
        /// </summary>
        public static string payload_dynamic_partition_metadata {
            get {
                return ResourceManager.GetString("payload_dynamic_partition_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error has occurred. 的本地化字符串。
        /// </summary>
        public static string payload_error_occur {
            get {
                return ResourceManager.GetString("payload_error_occur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore unknown operations 的本地化字符串。
        /// </summary>
        public static string payload_extract_ignore_unknown {
            get {
                return ResourceManager.GetString("payload_extract_ignore_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore checksum 的本地化字符串。
        /// </summary>
        public static string payload_extract_ignore_verify {
            get {
                return ResourceManager.GetString("payload_extract_ignore_verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract Image 的本地化字符串。
        /// </summary>
        public static string payload_extract_image {
            get {
                return ResourceManager.GetString("payload_extract_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow incremental 的本地化字符串。
        /// </summary>
        public static string payload_extract_incremental {
            get {
                return ResourceManager.GetString("payload_extract_incremental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extracting options 的本地化字符串。
        /// </summary>
        public static string payload_extract_options {
            get {
                return ResourceManager.GetString("payload_extract_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Package 的本地化字符串。
        /// </summary>
        public static string payload_full_package {
            get {
                return ResourceManager.GetString("payload_full_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to extract images from an incremental package. 的本地化字符串。
        /// </summary>
        public static string payload_incremental_warning {
            get {
                return ResourceManager.GetString("payload_incremental_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manifest Size 的本地化字符串。
        /// </summary>
        public static string payload_manifest_size {
            get {
                return ResourceManager.GetString("payload_manifest_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metadata Signatures (Base64) 的本地化字符串。
        /// </summary>
        public static string payload_metadata_signature {
            get {
                return ResourceManager.GetString("payload_metadata_signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metadata Signatures Size 的本地化字符串。
        /// </summary>
        public static string payload_metadata_signature_size {
            get {
                return ResourceManager.GetString("payload_metadata_signature_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No dynamic partition metadata 的本地化字符串。
        /// </summary>
        public static string payload_no_dynamic_metadata {
            get {
                return ResourceManager.GetString("payload_no_dynamic_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No payload has been specified, click the button browse, or drag in a file. 的本地化字符串。
        /// </summary>
        public static string payload_no_file_str {
            get {
                return ResourceManager.GetString("payload_no_file_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partitions Included:  的本地化字符串。
        /// </summary>
        public static string payload_partition_group_include {
            get {
                return ResourceManager.GetString("payload_partition_group_include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partition Group Name:  的本地化字符串。
        /// </summary>
        public static string payload_partition_group_name {
            get {
                return ResourceManager.GetString("payload_partition_group_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partition Group Size:  的本地化字符串。
        /// </summary>
        public static string payload_partition_group_size {
            get {
                return ResourceManager.GetString("payload_partition_group_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partitions 的本地化字符串。
        /// </summary>
        public static string payload_partitions {
            get {
                return ResourceManager.GetString("payload_partitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter by name: 的本地化字符串。
        /// </summary>
        public static string payload_partitions_filter_by_name {
            get {
                return ResourceManager.GetString("payload_partitions_filter_by_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checksum (Base64) 的本地化字符串。
        /// </summary>
        public static string payload_partitions_hash {
            get {
                return ResourceManager.GetString("payload_partitions_hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string payload_partitions_name {
            get {
                return ResourceManager.GetString("payload_partitions_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        public static string payload_partitions_size {
            get {
                return ResourceManager.GetString("payload_partitions_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string payload_property_name {
            get {
                return ResourceManager.GetString("payload_property_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        public static string payload_property_value {
            get {
                return ResourceManager.GetString("payload_property_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string payload_remove_file {
            get {
                return ResourceManager.GetString("payload_remove_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Signatures (Base64) 的本地化字符串。
        /// </summary>
        public static string payload_signature {
            get {
                return ResourceManager.GetString("payload_signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Signatures Size 的本地化字符串。
        /// </summary>
        public static string payload_signature_size {
            get {
                return ResourceManager.GetString("payload_signature_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snapshot enabled:  的本地化字符串。
        /// </summary>
        public static string payload_snapshot_enabled {
            get {
                return ResourceManager.GetString("payload_snapshot_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target partitions to extract not yet selected. 的本地化字符串。
        /// </summary>
        public static string payload_target_partition_not_selected {
            get {
                return ResourceManager.GetString("payload_target_partition_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timestamp 的本地化字符串。
        /// </summary>
        public static string payload_timestamp {
            get {
                return ResourceManager.GetString("payload_timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to drop multiple files. 的本地化字符串。
        /// </summary>
        public static string payload_unable_drop_multifile {
            get {
                return ResourceManager.GetString("payload_unable_drop_multifile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incompatible file format. 的本地化字符串。
        /// </summary>
        public static string payload_unsupported_format {
            get {
                return ResourceManager.GetString("payload_unsupported_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payload Version 的本地化字符串。
        /// </summary>
        public static string payload_version {
            get {
                return ResourceManager.GetString("payload_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The program is already running 的本地化字符串。
        /// </summary>
        public static string program_already_running {
            get {
                return ResourceManager.GetString("program_already_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Release at www.akr-developers.com 的本地化字符串。
        /// </summary>
        public static string release_at {
            get {
                return ResourceManager.GetString("release_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the path to save 的本地化字符串。
        /// </summary>
        public static string select_save_path {
            get {
                return ResourceManager.GetString("select_save_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        public static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thread 的本地化字符串。
        /// </summary>
        public static string visit_thread {
            get {
                return ResourceManager.GetString("visit_thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
